source "$(dirname "${BASH_SOURCE[0]}")/src/zsource.bash"
source "$(dirname "${BASH_SOURCE[0]}")/src/zrun.bash"
source "$(dirname "${BASH_SOURCE[0]}")/src/zset.bash"
source "$(dirname "${BASH_SOURCE[0]}")/src/overrides/source.bash"
source "$(dirname "${BASH_SOURCE[0]}")/src/overrides/run.bash"
