name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: shellcheck ./src/*

  test:
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest']
        include:
          - os: ubuntu-latest
            installzsh: true
    runs-on: ${{ matrix.os }}

    steps:
      - if: matrix.installzsh
        run: sudo apt-get install zsh

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install

      - name: Run bats tests
        run: npm test
